apiVersion: v1
kind: Service
metadata:
  name: {{ template "seaweedfs.name" . }}-webdav
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "seaweedfs.name" . }}
    component: webdav
spec:
  ports:
  - name: "swfs-webdav"
    port: {{ if .Values.webdav.enabled }}{{ .Values.webdav.port }}{{ else }}{{ .Values.filer.webdav.port }}{{ end }}
    targetPort: {{ if .Values.webdav.enabled }}{{ .Values.webdav.port }}{{ else }}{{ .Values.filer.webdav.port }}{{ end }}
    protocol: TCP
{{- if and .Values.webdav.enabled .Values.webdav.metricsPort }}
  - name: "metrics"
    port: {{ .Values.webdav.metricsPort }}
    targetPort: {{ .Values.webdav.metricsPort }}
    protocol: TCP
{{- end }}
  selector:
    app: {{ template "seaweedfs.name" . }}
    component: {{ if .Values.webdav.enabled }}webdav{{ else }}filer{{ end }}
