repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: clickhouse
    namespace: default
    chart: bitnami/clickhouse
    values:
      - image:
          tag: 23.4.1-debian-11-r0
      - shards: 1
      - replicaCount: 3
      - keeper:
          enabled: true
      - zookeeper:
          enabled: false
      - auth:
          password: 1
      - nodeSelector:
          country: finland
      - persistence:
          size: 30Gi
  - name: clickhouse-ingress
    namespace: default
    chart: main/raw
    values:
      - resources:
        - apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: clickhouse
            annotations:
              kubernetes.io/ingress.class: traefik
          spec:
            rules:
             - host: "gladiators.hattid.com"
               http:
                 paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: clickhouse
                        port:
                          number: 8123
             - host: "clickhouse.gladiators.io"
               http:
                 paths:
                  - path: /
                    pathType: Prefix
                    backend:
                      service:
                        name: clickhouse
                        port:
                          number: 8123
