repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: clickhouse
    namespace: default
    chart: bitnami/clickhouse
    values:
      - image:
          tag: 23.4.1-debian-11-r0
      - shards: 1
      - replicaCount: 3
      - keeper:
          enabled: true
      - zookeeper:
          enabled: false
      - auth:
          password: 1
      - nodeSelector:
          country: finland
      - persistence:
          size: 30Gi
