apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argo
  namespace: argo
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: "webhook.gladiators.dev"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: healthcheck-eventsource-svc
            port:
              number: 12000
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  namespace: argo
  name: healthcheck
spec:
  service:
    ports:
      - port: 12000
  webhook:
    # event-source can run multiple HTTP servers. Simply define a unique port to start a new HTTP server
    example:
      # port to run HTTP server on
      port: "12000"
      # endpoint to listen to
      endpoint: /example
      # HTTP request method to allow. In this case, only POST requests are accepted
      method: POST
