apiVersion: v1
kind: Service
metadata:
  name: {{ include "kopia-server.fullname" . }}
  labels:
    {{- include "kopia-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: kopia
      protocol: TCP
      name: kopia
  selector:
    {{- include "kopia-server.selectorLabels" . | nindent 4 }}
