
releases:
  - name: kopia-server
    namespace: db
    # createNamespace: true
    chart: ./kopia-server
    values:
      - secret.yaml
      - affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                  - xpand
