{{- $root := . -}}
{{- range .Values.nodes }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $root.Release.Name }}-{{ .name }}
data:
  config: |
{{- $rootConf := deepCopy $root.Values.common.client.config }}
{{ mergeOverwrite $rootConf .config | toYaml | indent 4 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ca-crt
data:
  ca.crt: |
{{ .Values.ca.public | indent 4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ssh
data:
  ssh.key: |
{{ .Values.ssh.key | indent 4 }}
