image:
  repository: apache/nifi
  tag: "1.18.0"
  pullPolicy: "IfNotPresent"


properties:
  sensitiveKey: changeMe # Must have at least 12 characters

auth:
  admin: CN=admin, OU=NIFI
  SSL:
    keystorePasswd: changeMe
    truststorePasswd: changeMe

  # Automaticaly disabled if OIDC or LDAP enabled
  singleUser:
    username: admin
    password: changeme # Must to have at least 12 characters

zookeeper:
  ## If true, install the Zookeeper chart
  ## ref: https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml
  enabled: true
  ## If the Zookeeper Chart is disabled a URL and port are required to connect
  # url: "zookeeper-hz.stage.dg"
  # port: 30921

jvmMemory: 1g

registry:
  enabled: false
  url: http://nifi-registry.default.svc.cluster.local
  port: 18080
  persistence:
    enabled: true
    database:
      storageClass: openebs-hostpath
    flowStorage:
      storageClass: openebs-hostpath


metrics:
  prometheus:
    enable: false

replicaCount: 1

persistence:
  enabled: true
  customStorageClass: true
  storageClass: local-path
  storageProvisioner: local-path

ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
  path: /
  tls:
    - hosts:
      - nifi-hz.stage.dg
  hosts:
    - nifi-hz.stage.dg
