image:
  repository: pihole/pihole
  tag: latest

resources:
  limits:
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 50Mi

config: |
  server=/stage.san/10.69.101.44#55
  server=/production.san/10.69.101.44#55
  server=/internal.san/10.69.101.44#55
  server=/cluster.local/10.46.0.10#55
  server=/clickhouse-0/100.64.0.10#55
  address=/nasduck.io/10.69.101.69
  address=/router.io/192.168.11.1
  address=/oracle.io/150.230.21.34
  address=/server.io/193.178.169.181
  address=/router.den/192.168.11.1
  address=/nasduck.den/192.168.11.58
  address=/nasduck.synology.me/10.69.101.69
  address=/dg/10.46.43.240
