{{- if .Values.ui.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "cruise.name" . }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ui.ingress.class | default "traefik" }}
spec:
  rules:
  - host: {{ .Values.ui.ingress.host | default "cruise.io" }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "cruise.name" . }}
            port:
              number: 8090
{{- end }}
