apiVersion: v1
kind: Service
metadata:
  name: {{ include "cruise.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "cruise.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - protocol: TCP
    name: http
    port: 8090
    targetPort: http
