apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "polynote.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
  - host: "polynote.dg"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "polynote.fullname" . }}
            port:
              number: 8192
      - path: /spark
        pathType: Prefix
        backend:
          service:
            name: {{ include "polynote.fullname" . }}
            port:
              number: 4040
  - host: "spark.dg"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "polynote.fullname" . }}
            port:
              number: 4040
