apiVersion: v1
kind: Service
metadata:
  name: {{ include "earthly.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "earthly.name" . }}
    helm.sh/chart: {{ include "earthly.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 600 # This should be longer than your build.
  ports:
    - protocol: TCP
      port: 8372
      targetPort: 8372
