apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloak.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "cloak.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    name: tls
    port: {{ .Values.service.port }}
    targetPort: 443
