environments:
  default:
    values:
      - secret.yaml

releases:
  - name: liquid-streamer
    namespace: bigdata
    chart: main/raw
    values:
      - resources:
        - apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: liquid-streamer
            labels:
              app: liquid-streamer
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: liquid-streamer
            template:
              metadata:
                labels:
                  app: liquid-streamer
              spec:
                imagePullSecrets:
                  - name: ghcr-login-secret
                containers:
                  - name: liquid-streamer
                    image: ghcr.io/the-analytics-gladiators/liquid-streamer:latest
                    env:
                      - name: ORACLE_PASS
                        value: "{{ .Values.oracle_pass }}"
                      - name: PAGE_SIZE
                        value: "5000"
                    livenessProbe:
                      exec:
                        command: # Healthcheck file was not updated for some time
                        - sh
                        - -c
                        - >-
                          find /tmp/healthcheck -mmin -5 | grep .
                      initialDelaySeconds: 360
                      periodSeconds: 30
        - apiVersion: v1
          kind: Service
          metadata:
            name: liquid-streamer
          spec:
            selector:
              app: liquid-streamer
            ports:
              - protocol: TCP
                port: 8088
                targetPort: 8088
