apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liquid8.fullname" . }}-config
data:
  logback.xml: |
    <configuration>
      <appender name="STDOUT"
      class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%-5level [%thread] %logger{10} - %msg%n</pattern>
        </encoder>
      </appender>
      <logger name="io.gladiators" level="DEBUG" />
      <root level="WARN">
        <appender-ref ref="STDOUT" />
      </root>
    </configuration>

  config.yaml: |
{{ .Values.config | indent 6 }}
