apiVersion: v1
kind: ConfigMap
metadata:
  name: liquid8-config
  annotations:
    "helm.sh/hook": "pre-install"
data:
  logback.xml: |
    <configuration>
      <appender name="STDOUT"
      class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{10} - %msg%n</pattern>
        </encoder>
      </appender>
      <logger name="io.gladiators" level="DEBUG" />
      <root level="WARN">
        <appender-ref ref="STDOUT" />
      </root>
    </configuration>

  config.yaml: |
{{ .Values.config | indent 6 }}
