apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liquid8.fullname" . }}
  labels:
    {{- include "liquid8.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "liquid8.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "liquid8.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "liquid8.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - sh
            - -c
            - "java -Dlogback.configurationFile=/app/logback.xml -Xmx1100m -Dfile.ending=UTF8 -jar /app/app.jar"
          livenessProbe:
            exec:
              command: # Healthcheck file was not updated for some time
              - sh
              - -c
              - >-
                find /tmp/healthcheck -mmin -30 | grep .
            initialDelaySeconds: 360
            periodSeconds: 30
          readinessProbe:
            exec:
              command: # Healthcheck file was not updated for some time
              - sh
              - -c
              - >-
                find /tmp/healthcheck -mmin -25 | grep .
            initialDelaySeconds: 200
            periodSeconds: 20
          env:
            - name: BSC_WALLET
              value: "{{ .Values.wallet_bsc }}"
            - name: trader
              value: big-dick-denis
          volumeMounts:
            - name: config
              mountPath: /app/logback.xml
              subPath: logback.xml
              readOnly: true
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "liquid8.fullname" . }}-config
