apiVersion: v1
kind: Service
metadata:
  name: {{ include "hattid.fullname" . }}-front
  labels:
    {{- include "hattid.front.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: {{ .Values.front.service.port }} 
      protocol: TCP
  selector:
    {{- include "hattid.front.selectorLabels" . | nindent 4 }}
