apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-loader-config
data:
  application.conf: |
    tokens {
      authToken = {{ .Values.hattrick_secrets.accessToken }}
      authCustomerKey = {{ .Values.hattrick_secrets.customerKey }}
      clientSecret = {{ .Values.hattrick_secrets.customerSecret }}
      tokenSecret = {{ .Values.hattrick_secrets.accessTokenSecret }}
    }

    telegram {
      botToken = "{{ .Values.telegram.botToken }}"
      chatId = {{ .Values.telegram.chatId }}
    }
    
    database_name = "{{ .Values.loader.clickhouse.database }}"
    hattid_web_url = "http://{{ include "hattid.fullname" . }}-web:9000"
    
    akka.http.host-connection-pool.response-entity-subscription-timeout = 3.minute
    akka.stream.materializer.max-input-buffer-size = 512
    
    akka.http.host-connection-pool.max-connections = 512
    akka.http.host-connection-pool.max-open-requests = 512
    
    crobox.clickhouse.client {
        connection: {
            type = "single-host",
            host = "{{ .Values.loader.clickhouse.host }}",
            port = {{ .Values.loader.clickhouse.port }}
        }
        authentication {
            user = "{{ .Values.loader.clickhouse.user }}"
            password = ""
        }
    
        custom {
            send_logs_level = "trace"
        }
    }
    
    crobox.clickhouse.indexer {
         batch-size = 1500
         retries = 0
         concurrent-requests = 1
         flush-interval = 1 day
         fast-indexer {
             flush-interval = 1 second
             batch-size = 2000000
         }
       }
    
    my-dispatcher {
        type = "Dispatcher"
        executor = "fork-join-executor"
    
        fork-join-executor {
            parallelism-min = 100
            parallelism-factor = 8.0
            parallelism-max = 200
        }
    
        thread-pool-executor {
            keep-alive-time = 60s
            core-pool-size-min = 80
            core-pool-size-factor = 8.0
            core-pool-size-max = 256
            max-pool-size-min = 80
            max-pool-size-factor  = 8.0
            max-pool-size-max = 256
            task-queue-size = -1
            task-queue-type = "linked"
    
            allow-core-timeout = on
        }
    }
    
    akka.actor.default-dispatcher = ${my-dispatcher}

