apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-web-config
data:
  configuration.conf: |
    hattrick {
      customerKey = "{{ .Values.hattrick_secrets.customerKey }}"
      customerSecret = "{{ .Values.hattrick_secrets.customerSecret }}"
      accessToken = "{{ .Values.hattrick_secrets.accessToken }}"
      accessTokenSecret = "{{ .Values.hattrick_secrets.accessTokenSecret }}"
    }

    ho {
      customerKey = "{{ .Values.hattrick_secrets.hoCustomerKey }}"
      customerSecret = "{{ .Values.hattrick_secrets.hoCustomerSecret }}"
    }

    db.default.driver = ru.yandex.clickhouse.ClickHouseDriver
    db.default.url = "{{ .Values.web.dbUrl }}"
    db.default.logStatements=true

    fixedConnectionPool = 20
