apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: likeforce
  labels:
    app: likeforce
spec:
  schedule: '{{ "012345" | shuffle | substr 0 2 }} */12 * * *' # every 12 hours with poor man randomization ;)
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 43200 # 12 hours k8s GC to clean up finished Jobs
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: likeforce
              image: ghcr.io/wonderbeat/likeforce:likeforce
              resources:
                requests:
                  memory: "100M"
                limits:
                  memory: "200M"
                  cpu: "1"
              imagePullPolicy: Always
              imagePullSecret:
                - name: ghcr-login-secret
              env:
                - name: code
                  value: "43d7db68517188e2f8"
              # command: [ "sh", "-c", "python3 src/flink_savepoints/main.py"]
