apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include ".fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      {{- include ".selectorLabels" . | nindent 6 -}}

