releases:
  - name: storage
    chart: main/raw
    values:
      - resources:
        - apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: ssd-200-gb
          provisioner: rancher.io/local-path
          parameters:
            nodePath: /mnt/HC_Volume_100344116
          reclaimPolicy: Retain


