# Default values for haproxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: haproxy
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nodeSelector:
  "kubernetes.io/hostname": jonapot

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  port: 80

config: |-
  defaults
    mode http
    timeout client 10s
    timeout connect 5s
    timeout server 10s
    timeout http-request 10s
  frontend public_web_servers
    mode http
    log global
    timeout client 30s
    bind *:80
    default_backend public_web_servers

  frontend api_servers
    mode http
    log global
    timeout client 30s
    bind *:8000
    default_backend api_servers

  backend public_web_servers
    mode http
    balance roundrobin
    server s1 192.168.1.25:80
    server s2 192.168.1.26:80

  backend api_servers
    mode http
    balance roundrobin
    server s1 192.168.1.27:8000
    server s2 192.168.1.28:8080
