repositories:
  - name: andrcuns
    url: https://andrcuns.github.io/charts
releases:
  - name: buildkit
    namespace: ci
    chart: andrcuns/buildkit-service
    values:
      - image:
          tag: v0.29.0
      - buildkitdToml: |
          debug = true
          insecure-entitlements = [ "network.host" ]
          [registry."harbor-core.db.svc.cluster.local:80"]
              http = true
          [registry."harbor-core.db.svc.cluster.local"]
              http = true
          [registry."harbor-core.db"]
              http = true
          [registry."docker.io"]
              mirrors = ["harbor-core.db/docker-mirror"]
          [registry."ghcr.io"]
              mirrors = ["harbor-core.db/github-mirror"]
          [dns]
              nameservers = ["10.46.0.10"]
              searchdomains = ["db.svc.cluster.local", "svc.cluster.local", "cluster.local"]
      - env:
          - name: BUILDKIT_NO_CLIENT_TOKEN
            value: "1"
      - resources:
          requests:
            memory: 300Mi
          limits:
            memory: 2Gi
      #- rootless: true
      - affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - jonapot
