repositories:
  - name: andrcuns
    url: https://andrcuns.github.io/charts
releases:
  - name: buildkit
    namespace: ci
    chart: andrcuns/buildkit-service
    values:
      - image:
          tag: rootless
      - buildkitdToml: |
          debug = false
          [worker.oci]
              enabled = true
              rootless = true
              max-parallelism = 2
          [registry."docker.io"]
              mirrors = ["harbor.gladiators.dev/docker-mirror"]
          [registry."ghcr.io"]
              mirrors = ["harbor.gladiators.dev/github-mirror"]
      - resources:
          requests:
            memory: 300Mi
          limits:
            memory: 2Gi
      - rootless: true
      - affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - jonapot
