apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pihole.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  serviceName: pihole
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pihole.name" . }}
      helm.sh/chart: {{ include "pihole.chart" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "pihole.name" . }}
        helm.sh/chart: {{ include "pihole.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: pihole
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: 53
            - containerPort: 80
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/dnsmasq.d/10-custom.conf
              subPath: 10-custom.conf
              readOnly: true
            - name: etc
              mountPath: /etc/pihole
{{- if .Values.resources }}
          resources:
{{ toYaml .Values.resources | indent 12}}
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "pihole.fullname" . }}-config
  volumeClaimTemplates:
  - metadata:
      name: etc
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
      # storageClassName:
