apiVersion: v1
kind: Service
metadata:
  name: {{ include "pihole.name" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "pihole.name" . }}
    helm.sh/chart: {{ include "pihole.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  type: ClusterIP
  ports:
  - protocol: UDP
    name: dns
    port: 53
    targetPort: 53
  - protocol: TCP
    name: admin
    port: 80
    targetPort: 80
