#	kubectl create job -n bigdata --from="cronjob/liquid8" liquid8

environments:
  default:
    values:
      - secret.yaml
releases:
  - name: liquid8
    namespace: bigdata
    createNamespace: true
    chart: ./liquid8
    values:
      - secret.yaml
      - env:
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: http/protobuf
          - name: OTEL_LOGS_EXPORTER
            value: none
          - name: OTEL_INSTRUMENTATION_OKHTTP_ENABLED
            value: false
          - name: OTEL_METRICS_EXPORTER
            value: none
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://$(HOST_IP):4318

      - config: |
          wssNodesFile: /wss-nodes.txt
          httpNodesFile: /nodes.txt
          historicalUpdatesBlocks: 7000
          blockchain: binance
          blockBuilderEnabled: true
          trampolineDeadlineMillis: 450
          tradingTokens:
          - 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
          - 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
          - 0x55d398326f99059fF775485246999027B3197955

  # - name: liquid8-polygon
  #   namespace: bigdata
  #   chart: ./liquid8
  #   values:
  #     - secret.yaml
  #     - config: |
  #         blockchain: polygon
  #         wssNodesFile: /wss-nodes.polygon.txt
  #         httpNodesFile: /nodes.polygon.txt
  #         historicalUpdatesBlocks: 300
  #         blockBuilderEnabled: false
  #         trampolineDeadlineMillis: 2000 # whole block
  #         tradingTokens:
  #           - 0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270
  #         grossCycleIncomeThresholdInCents: 1
