environments:
  default:
    values:
    - default.yaml
---

releases:
  - name: dapr-pubsub-liquid8
    namespace: bigdata
    chart: main/raw
    values:
      - secrets-pubsub.yaml

  - name: dapr-subscription-bsc
    namespace: bigdata
    chart: main/raw
    values:
      - resources:
          - apiVersion: dapr.io/v2alpha1
            kind: Subscription
            metadata:
              name: execute
            spec:
              topic: opportunity-bsc
              routes:
                default: /execute
              pubsubname: liquid-pubsub
            scopes:
            - liquid-executor-bsc

  - name: liquid8-executor-bsc
    namespace: bigdata
    createNamespace: true
    chart: ./liquid8
    values:
      - podAnnotations:
          dapr.io/enabled: "true"
          dapr.io/app-id: "liquid-executor-bsc"
          dapr.io/app-port: "8080"
      - secret.yaml
      - env:
{{ .Values.env | toYaml | indent 8 }}
        - name: OTEL_SERVICE_NAME
          value: liquid8-executor-bsc
        - name: entrypoint
          value: executor
      - persistence:
          enabled: false
      - resources:
          requests:
            memory: 200Mi
          limits:
            memory: 300Mi
      - config: |
          historicalUpdatesBlocks: 7000
          blockchain: BSC
          trampolineDeadlineMillis: 550
          canaryThresholdUsd: 0.3
          swapGasLimit: 2400000
          grossCycleIncomeThresholdInUsd: 0.001
          mode: DAPR
          minimumNativeBalanceInUsd: 230
          tradingTokens:
          - 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
          - 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
          - 0x55d398326f99059fF775485246999027B3197955
          # eth
          # - 0x2170Ed0880ac9A755fd29B2688956BD959F933F8
          - 0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d
          blockBuilder:
            enabled: true
            thresholdUsd: 0.8
            feePart: 0.69

  - name: liquid8-searcher-bsc
    namespace: bigdata
    createNamespace: true
    chart: ./liquid8
    values:
      - podAnnotations:
          dapr.io/enabled: "true"
          dapr.io/app-id: "liquid-searcher-bsc"
          dapr.io/app-port: "8080"
      - secret.yaml
      - env:
{{ .Values.env | toYaml | indent 8 }}
        - name: OTEL_SERVICE_NAME
          value: liquid8-searcher-bsc
        - name: entrypoint
          value: searcher
      - config: |
          mode: DAPR
          historicalUpdatesBlocks: 7000
          blockchain: BSC
          trampolineDeadlineMillis: 550
          canaryThresholdUsd: 0.3
          swapGasLimit: 2400000
          grossCycleIncomeThresholdInUsd: 0.001
          minimumNativeBalanceInUsd: 230
          tradingTokens:
          - 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
          - 0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56
          - 0x55d398326f99059fF775485246999027B3197955
          # eth
          # - 0x2170Ed0880ac9A755fd29B2688956BD959F933F8
          - 0x8AC76a51cc950d9822D68b83fE1Ad97B32Cd580d
          blockBuilder:
            enabled: true
            thresholdUsd: 0.8
            feePart: 0.69

      - affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - usa
