#	kubectl create job --from="cronjob/liquid8" liquid8

environments:
  default:
    values:
      - secret.yaml
releases:
  - name: liquid8
    namespace: bigdata
    chart: main/raw
    values:
      - resources:
          - apiVersion: batch/v1
            kind: CronJob
            metadata:
              name: liquid8
              labels:
                app: liquid8
            spec:
              schedule: '*/50 * * * *' # every 9 minutes
              concurrencyPolicy: Forbid
              successfulJobsHistoryLimit: 1
              failedJobsHistoryLimit: 2
              jobTemplate:
                spec:
                  ttlSecondsAfterFinished: 43200 # 12 hours k8s GC to clean up finished Jobs
                  backoffLimit: 0
                  template:
                    spec:
                      restartPolicy: Never
                      imagePullSecrets:
                        - name: ghcr-login-secret
                      containers:
                        - name: liquid8
                          image: ghcr.io/the-analytics-gladiators/liquid8:liquid8
                          resources:
                            requests:
                              memory: "100M"
                            limits:
                              memory: "300M"
                              cpu: "2"
                          imagePullPolicy: Always
                          env:
                            - name: BSC_WALLET
                              value: "{{ .Values.wallet_bsc }}"
                          # command: [ "sh", "-c", "python3 src/flink_savepoints/main.py"]
                          volumeMounts:
                            - name: logger
                              mountPath: /app/logback.xml
                              subPath: logback.xml
                              readOnly: true
                          command: ["/usr/bin/timeout", "49m", "java", "-jar","/app/app.jar"]
                      volumes:
                        - name: logger
                          configMap:
                            name: liquid8-logger
  - name: liquid8-logger
    namespace: bigdata
    chart: main/raw
    needs:
      - liquid8
    values:
      - resources:
          - apiVersion: v1
            kind: ConfigMap
            metadata:
              name: liquid8-logger
              annotations:
                "helm.sh/hook": "pre-install"
            data:
              logback.xml: |-
                <configuration>
                  <appender name="STDOUT"
                  class="ch.qos.logback.core.ConsoleAppender">
                    <encoder>
                      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{10} -
                      %msg%n</pattern>
                    </encoder>
                  </appender>
                  <logger name="io.gladiators" level="DEBUG" />
                  <root level="WARN">
                    <appender-ref ref="STDOUT" />
                  </root>
                </configuration>
