sidecars:
  livenessProbeImage:
    repository: k8s.gcr.io/sig-storage/livenessprobe
    tag: "v2.6.0"
  nodeDriverRegistrarImage:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: "v2.5.0"
  # csiProvisionerImage:
  #   repository: k8s.gcr.io/sig-storage/csi-provisioner
  #   tag: "v2.0.2"


controller:
  resources:
  limits:
    cpu: 1000m
    memory: 512Gi
  requests:
    cpu: 100m
    memory: 100Mi

node:
  resources:
    limits:
      cpu: 1000m
      memory: 512Gi
    requests:
      cpu: 100m
      memory: 100Mi

  mountPod:
    resources:
      limits:
        cpu: 5000m
        memory: 512Mb
      requests:
        cpu: 10m
        memory: 50Mb
