repositories:
  - name: harbor
    url: https://helm.goharbor.io
releases:
  - name: harbor-middleware
    namespace: db
    chart: main/raw
    values:
      - resources:
          - apiVersion: traefik.containo.us/v1alpha1
            kind: Middleware
            metadata:
              name: harbor-proxy-headers-magic
            spec:
              headers:
                customRequestHeaders:
                  X-Forwarded-Proto: "https"
  - name: harbor
    namespace: db
    chart: harbor/harbor
    values:
      - database:
          internal:
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                  - matchExpressions:
                    - key: kubernetes.io/arch
                      operator: In
                      values:
                        - amd64
            resources:
              limits:
                memory: "300Mi"
              requests:
                memory: "50Mi"
      - portal:
          image:
            repository: bitnami/harbor-portal
            tag: 2.12.2
          resources:
            limits:
              memory: "300Mi"
            requests:
              memory: "50Mi"
      - core:
          replicas: 1
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                  - key: kubernetes.io/hostname
                    operator: NotIn
                    values:
                      - xpand
          resources:
            limits:
              memory: "300Mi"
            requests:
              memory: "50Mi"

      - jobservice:
          maxJobWorkers: 1
          jobLoggers:
            - stdout
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
          replicas: 1
          resources:
            limits:
              memory: "300Mi"
            requests:
              memory: "50Mi"
      - registry:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
          controller:
            image:
              repository: bitnami/harbor-registryctl
              tag: 2.12.2
          registry:
            resources:
              limits:
                memory: "300Mi"
              requests:
                memory: "50Mi"
      - expose:
          tls:
            enabled: false
          ingress:
            hosts:
              core: harbor.gladiators.dev
              className: traefik
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: db-harbor-proxy-headers-magic@kubernetescrd

      - externalURL: https://harbor.gladiators.dev
      - persistence:
          resourcePolicy: drop
      - trivy:
          enabled: false
      - redis:
          type: external
          external:
            addr: redis-master.db.svc.cluster.local:6379
      - logLevel: error
      - secret.yaml
