releases:
  - name: tailscale
    namespace: network
    createNamespace: true
    chart: ./tailscale-userspace
    values:
      - service:
          enabled: true
      - affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - xpand
                  - vm
