repositories:
  - name: datadog
    url: https://helm.datadoghq.com
releases:
  - name: datadog
    namespace: monitoring
    chart: datadog/datadog
    historyMax: 1
    values:
      - datadog:
          logs:
            enabled: true
            containerCollectAll: true
            resources:
              limits:
                cpu: 200m
                memory: 256Mi
          site: datadoghq.com
          clusterName: mastermind
          prometheusScrape:
            enabled: true
            serviceEndpoints: true
      - clusterChecksRunner:
        # image:
        #   tag: 7.39.2
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 50Mi
      - clusterAgent:
          # image:
          #   tag: 7.39.2
          resources:
            limits:
              cpu: 0.5
              memory: 256Mi
            requests:
              cpu: 0.1
              memory: 40Mi
      - agents:
          # tolerations:
          # - key: "dedicated"
          #   operator: "Equal"
          #   value: "small"
          #   effect: NoSchedule
          # image:
          #   tag: 7.39.2
          containers:
            agent:
              logLevel: WARN
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
              requests:
                cpu: 10m
                memory: 50Mi
            processAgent:
              logLevel: WARN
              resources:
                limits:
                  cpu: 200m
                  memory: 110Mi
                requests:
                  cpu: 10m
                  memory: 50Mi
            traceAgent:
              logLevel: WARN
              resources:
                limits:
                  cpu: 200m
                  memory: 100Mi
                requests:
                    cpu: 0.1
                    memory: 70Mi
      - secrets.yaml

  - name: restrict-policy-ko
    namespace: monitoring
    chart: incubator/raw
    # needs:
    #   - kyverno/kyverno
    values:
      - resources:
          - apiVersion: kyverno.io/v1
            kind: ClusterPolicy
            metadata:
              name: restrict-agent
              annotations:
                policies.kyverno.io/title: Restrict agent
                policies.kyverno.io/subject: Pod
                policies.kyverno.io/category: Other
                policies.kyverno.io/description: >-
                  Can't override requests/limits without this
            spec:
              rules:
              - name: add-default-requests
                match:
                  any:
                  - resources:
                      kinds:
                        - Pod
                      namespaces:
                        - monitoring
                preconditions:
                  any:
                  - key: "{{`{{request.operation || 'BACKGROUND' }}`}}"
                    operator: AnyIn
                    value:
                    - CREATE
                    - UPDATE
                mutate:
                  patchStrategicMerge:
                    spec:
                      containers:
                      - (name): agent
                        resources:
                          requests:
                            memory: "120Mi"
                            cpu: "10m"
                          limits:
                            memory: "200Mi"
                            cpu: "200m"
