environments:
  default:
    values:
      - secret.users.yaml
---
releases:
  - name: clickhouse-arm
    namespace: db
    chart: main/raw
    values:
      - resources:
        - apiVersion: batch/v1
          kind: CronJob
          metadata:
            name: clickhouse-arm-backup
            labels:
              app: clickhouse-arm-backup
          spec:
            schedule: "0 18 * * MON"
            jobTemplate:
              spec:
                template:
                  spec:
                    containers:
                     - name: clickhouse-backup
                       image: clickhouse:26.3.3.20-jammy
                       command:
                         - "/bin/sh"
                         - "-ec"
                         - |
                           MONDAY=$(clickhouse-client -h clickhouse-arm -q "select toMonday(today())") 
                           PREVIOUS_MONDAY=$(clickhouse-client -h clickhouse-arm -q "select toMonday(today() - 7)") 
                           clickhouse-client -h clickhouse-arm -q "BACKUP DATABASE hattrick TO S3('https://gladiators-clickhouse-backup.s3.amazonaws.com/hattrick-$MONDAY', '{{ .Values.aws_access_key }}', '{{ .Values.aws_secret_key }}') SETTINGS base_backup = S3('https://gladiators-clickhouse-backup.s3.amazonaws.com/hattrick-$PREVIOUS_MONDAY', '{{ .Values.aws_access_key }}', '{{ .Values.aws_secret_key }}')" --send_timeout 7200 --receive_timeout 7200
                    restartPolicy: OnFailure
        - apiVersion: v1 
          kind: ConfigMap
          metadata:
            name: clickhouse-arm-config
          data:
            users.xml: |
{{ .Values.config | indent 14 }}
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: clickhouse-ssd-pvc
            namespace: "db"
            annotations:
              volume.kubernetes.io/selected-node: apol
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: clickhouse-ssd
            resources:
              requests:
                storage: 250Gi

        - apiVersion: apps/v1
          kind: StatefulSet
          metadata: 
            name: clickhouse-arm
            labels:
              app: clickhouse-arm
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: clickhouse-arm
            template:
              metadata:
                labels:
                  app: clickhouse-arm
              spec:
                containers:
                  - name: clickhouse-arm
                    image: clickhouse:26.3.3.20-jammy
                    volumeMounts:
                      - name: clickhouse-data
                        mountPath: /var/lib/clickhouse
                      - name: users-config
                        mountPath: /etc/clickhouse-server/users.d
                    resources:
                      limits:
                        memory: "6G"
                volumes:
                  - name: users-config
                    configMap:
                      name: clickhouse-arm-config
                  - name: clickhouse-data
                    persistentVolumeClaim:
                      claimName: clickhouse-ssd-pvc

        - apiVersion: v1
          kind: Service
          metadata:
            name: clickhouse-arm
          spec:
            selector:
              app: clickhouse-arm
            ports:
              - protocol: TCP
                name: http
                port: 8123
                targetPort: 8123
              - protocol: TCP
                name: native
                port: 9000
                targetPort: 9000
