environments:
  default:
    values:
      - secret.users.yaml
releases:
  - name: clickhouse-standalone
    namespace: db
    chart: main/raw
    values:
      - resources:
        - apiVersion: v1
          kind: ConfigMap
          metadata:
            name: clickhouse-config
          data:
            users.xml: |
{{ .Values.config | indent 14 }}
        - apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: ssd-200gb-pvc
            namespace: "db"
            annotations:
              volume.kubernetes.io/selected-node: k8s-2
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: ssd-200-gb
            resources:
              requests:
                storage: 200Gi
        - apiVersion: apps/v1
          kind: StatefulSet
          metadata: 
            name: clickhouse
            labels:
              app: clickhouse
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: clickhouse
            template:
              metadata:
                labels:
                  app: clickhouse
              spec:
                containers:
                  - name: clickhouse
                    image: clickhouse/clickhouse-server:24.1.2.5-alpine
                    volumeMounts:
                      - name: ch-data
                        mountPath: /var/lib/clickhouse
                      - name: users-config
                        mountPath: /etc/clickhouse-server/users.d
                volumes:
                  - name: users-config
                    configMap:
                      name: clickhouse-config
                  - name: ch-data
                    persistentVolumeClaim:
                      claimName: ssd-200gb-pvc
        - apiVersion: v1
          kind: Service
          metadata:
            name: clickhouse-standalone
          spec:
            selector:
              app: clickhouse
            ports:
              - protocol: TCP
                port: 8123
                targetPort: 8123
