repositories:
  - name: fluent
    url: https://fluent.github.io/helm-charts
releases:
  - name: fluent-bit
    namespace: monitoring
    chart: fluent/fluent-bit
    values:
      - secrets.yaml
      - flush: 13
      # - logLevel: warn
      - image:
          tag: 2.2.2
      - extraPorts:
          - name: otel
            protocol: TCP
            port: 4318
            containerPort: 4318
      - resources:
          requests:
            cpu: 1m
            memory: 10Mi
      - affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - jonapot
