---
# Source: hattid/templates/loader-job.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hattid-loader-temp
  labels:
    helm.sh/chart: hattid-0.1.0-loader
    app.kubernetes.io/name: hattid-loader
    app.kubernetes.io/instance: hattid-loader-loader
    app.kubernetes.io/managed-by: Helm-loader
spec:
  schedule: 08 * * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    ttlSecondsAfterFinished: 3200
    successfulJobsHistoryLimit: 2
    backoffLimit: 0
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: config
              configMap:
                name: hattid-loader-loader-config
          affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: kubernetes.io/hostname
                          operator: In
                          values:
                            - k8s-2

          containers:
            - name: hattid-web
              image: ghcr.io/blackmorse/hat-all-stats/akka_loader:latest
              imagePullPolicy: Always
              resources:
                limits:
                  memory: 3G
              env:
                - name: AKKA_CONFIG
                  value: /config/application.conf
              volumeMounts:
                - name: config
                  mountPath: /config
              command:
                - java
                - "-Dconfig.file=/config/application.conf"
                - -jar
                - /app/akka-loader-assembly-0.1.jar
                - loadScheduled
                - --entity
                - league


