# apiVersion: v1
# kind: Service
# metadata:
#   name: {{ include "nebula-lighthouse.fullname" . }}
#   labels:
#     {{- include "nebula-lighthouse.labels" . | nindent 4 }}
# spec:
#   type: NodePort
#   ports:
#     - port: {{ .Values.service.port }}
#       targetPort: http
#       protocol: {{ .Values.service.protocol }}
#       name: udp
#       nodePort: {{ .Values.service.port }}
#   type: NodePort
#   selector:
#     {{- include "nebula-lighthouse.selectorLabels" . | nindent 4 }}
