# Default values for nebula-lighthouse.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nebulaoss/nebula
  pullPolicy: IfNotPresent
  tag: "1.9.3"

  # repository: renehonig/nebula
  # pullPolicy: IfNotPresent
  # tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  capabilities:
    add:
      - NET_ADMIN

volumes:
  - name: devices
    hostPath:
      path: /dev


volumeMounts:
  - mountPath: /dev
    name: devices
  # capabilities:
  #     add:
  #       - NET_BROADCAST
  #       - NET_ADMIN
  #       - NET_RAW
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  port: 32243
  protocol: UDP

resources:
  limits:
    memory: 228Mi
  requests:
    memory: 80Mi

livenessProbe: {}
  # httpGet:
  #   path: /
  #   port: http
readinessProbe: {}
  # httpGet:
  #   path: /
  #   port: http

# Additional volumes on the output Deployment definition.

nodeSelector: {}

tolerations: []

affinity: {}
