apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polynote-pvc
  namespace: "bigdata"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 600M
  storageClassName: juicefs-sc
