apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polynote-pvc
  namespace: "bigdata"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: seaweedfs-storage
