apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: polynote-pvc
  namespace: "bigdata"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: oracle-fs
