# pg_dump -U coder coder > /tmp/coder.sql
# psql -U coder -d coder < /tmp/coder.sql
repositories:
  - name: coder-v2
    url: https://helm.coder.com/v2
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: coder-db
    namespace: db
    createNamespace: true
    chart: bitnami/postgresql
    values:
      - primary:
          resources:
            requests:
                memory: 400Mi
            limits:
                memory: 600Mi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - germany
      - secret.yaml
  - name: coder
    namespace: coder
    createNamespace: true
    chart: coder-v2/coder
    values:
      - coder:
          # image:
          #   tag: v2.10.2
          env:
            # - name: CODER_DERP_SERVER_ENABLE
            #   value: "false"
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  # You'll need to create a secret called coder-db-url with your
                  # Postgres connection URL like:
                  # postgres://coder:password@postgres:5432/coder?sslmode=disable
                  name: coder-db-url
                  key: url
            - name: CODER_ACCESS_URL
              value: "https://coder.gladiators.dev"
          ingress:
            enable: true
            className: traefik
            host: coder.gladiators.dev
          service:
            enable: true
            type: ClusterIP

  - name: coder-permissions
    namespace: coder
    chart: main/raw
    values:
      - resources:
        - apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: coder-user
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: Role
          metadata:
            name: coder-pod-creator
          rules:
          - apiGroups: [""]
            resources: ["pods", "secrets", "pods/exec", "deployments", "services", "pods/portforward"]
            verbs: ["create", "get", "watch", "list", "delete", "update"]
          - apiGroups: [""]
            resources: ["pods/log"]
            verbs: ["create", "get", "watch", "list"]
          - apiGroups: ["apps"]
            resources: ["deployments", "statefulsets"]
            verbs: ["create", "get", "watch", "list", "delete", "update", "patch"]
          - apiGroups: ["networking.k8s.io"]
            resources: ["ingresses"]
            verbs: ["create", "get", "watch", "list", "patch", "update"]

        - apiVersion: rbac.authorization.k8s.io/v1
          kind: RoleBinding
          metadata:
            name: coder-pod-creator
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: Role
            name: coder-pod-creator
          subjects:
          - kind: ServiceAccount
            name: coder-user

  # - name: coder-bigdata-permissions
  #   namespace: bigdata-coder
  #   createNamespace: true
  #   chart: main/raw
  #   values:
  #     - resources:
  #       - apiVersion: v1
  #         kind: ServiceAccount
  #         metadata:
  #           name: coder-user
  #       - apiVersion: rbac.authorization.k8s.io/v1
  #         kind: Role
  #         metadata:
  #           name: coder-pod-creator
  #         rules:
  #         - apiGroups: [""]
  #           resources: ["pods", "secrets", "pods/exec", "deployments"]
  #           verbs: ["create", "get", "watch", "list", "delete"]
  #         - apiGroups: [""]
  #           resources: ["pods/log"]
  #           verbs: ["create", "get", "watch", "list"]
  #       - apiVersion: rbac.authorization.k8s.io/v1
  #         kind: RoleBinding
  #         metadata:
  #           name: coder-pod-creator
  #         roleRef:
  #           apiGroup: rbac.authorization.k8s.io
  #           kind: Role
  #           name: coder-pod-creator
  #         subjects:
  #         - kind: ServiceAccount
  #           name: coder-user
