repositories:
  - name: coder-v2
    url: https://helm.coder.com/v2
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: coder-db
    namespace: db
    createNamespace: true
    chart: bitnami/postgresql
    values:
      - primary:
          resources:
            requests:
                memory: 400Mi
            limits:
                memory: 600Mi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - germany
      - secret.yaml
  - name: coder
    namespace: coder
    createNamespace: true
    chart: coder-v2/coder
    values:
      - coder:
        # You can specify any environment variables you'd like to pass to Coder
        # here. Coder consumes environment variables listed in
        # `coder server --help`, and these environment variables are also passed
        # to the workspace provisioner (so you can consume them in your Terraform
        # templates for auth keys etc.).
        #
        # Please keep in mind that you should not set `CODER_HTTP_ADDRESS`,
        # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
        # they are already set by the Helm chart and will cause conflicts.
          env:
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  # You'll need to create a secret called coder-db-url with your
                  # Postgres connection URL like:
                  # postgres://coder:password@postgres:5432/coder?sslmode=disable
                  name: coder-db-url
                  key: url
            - name: CODER_ACCESS_URL
              value: "https://coder.gladiators.dev"
          ingress:
            enable: true
            className: traefik
            host: coder.gladiators.dev
          service:
            enable: true
            type: ClusterIP
