# pg_dump -U coder coder > /tmp/coder.sql
# psql -U coder -d coder < /tmp/coder.sql
repositories:
  - name: coder-v2
    url: https://helm.coder.com/v2
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: coder-db
    namespace: db
    createNamespace: true
    chart: bitnami/postgresql
    values:
      - primary:
          resources:
            requests:
                memory: 400Mi
            limits:
                memory: 600Mi
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: topology.kubernetes.io/zone
                    operator: In
                    values:
                      - germany
      - secret.yaml
  - name: coder
    namespace: coder
    createNamespace: true
    chart: coder-v2/coder
    values:
      - coder:
          # image:
          #   tag: v2.10.2
          env:
            - name: CODER_PG_CONNECTION_URL
              valueFrom:
                secretKeyRef:
                  # You'll need to create a secret called coder-db-url with your
                  # Postgres connection URL like:
                  # postgres://coder:password@postgres:5432/coder?sslmode=disable
                  name: coder-db-url
                  key: url
            - name: CODER_ACCESS_URL
              value: "https://coder.gladiators.dev"
          ingress:
            enable: true
            className: traefik
            host: coder.gladiators.dev
          service:
            enable: true
            type: ClusterIP
