repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: redis
    namespace: db
    chart: bitnami/redis
    historyMax: 2
    values:
      - image:
          repository: redis
          tag: latest
      - auth:
          enabled: false
          password: password
      - replica:
          resources:
            requests:
              cpu: 100m
              memory: 30Mi
            limits:
              cpu: 2
              memory: 300Mi
      - master.resources:
          requests:
            cpu: 100m
            memory: 30Mi
          limits:
            cpu: 2
            memory: 300Mi
      - replica.replicaCount: 3
