repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: redis
    namespace: db
    chart: bitnami/redis
    values:
      - image:
          repository: redis
          tag: latest
      - auth:
          enabled: false
          password: password
      - replica:
          resources:
            requests:
              cpu: 100m
              memory: 30Mi
            limits:
              cpu: 2
              memory: 300Mi
      - master:
          nodeSelectors:
            dg.alwaysRunning: "true"
          resources:
            requests:
              cpu: 100m
              memory: 30Mi
            limits:
              cpu: 2
              memory: 300Mi
      - replica:
          replicaCount: 2
      - master:
          configuration: "appendfsync everysec"
