repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: redis
    namespace: db
    chart: bitnami/redis
    values:
      - image:
          repository: redis
          tag: latest
      - auth:
          enabled: false
          password: password
      - replica:
          readinessProbe:
            initialDelaySeconds: 180
            periodSeconds: 60
          resources:
            requests:
              memory: 300Mi
            limits:
              memory: 400Mi
      - master:
          nodeSelectors:
            dg.alwaysRunning: "true"
          resources:
            requests:
              memory: 600Mi
            limits:
              memory: 700Mi
          persistence:
            existingClaim: redis-data-redis-master-0
      - replica:
          replicaCount: 0
          configuration: |
            maxmemory 280mb
      - master:
          configuration: |
            appendfsync everysec
            maxmemory 600mb
            tcp-keepalive 0
