repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
releases:
  - name: redis
    namespace: db
    chart: bitnami/redis
    values:
      - image:
          repository: redis
          tag: latest
      - auth:
          enabled: false
          password: password
      - replica:
          resources:
            requests:
              memory: 90Mi
            limits:
              memory: 300Mi
      - master:
          nodeSelectors:
            dg.alwaysRunning: "true"
          resources:
            requests:
              memory: 1000Mi
            limits:
              memory: 1000Mi
          persistence:
            existingClaim: redis-data-redis-master-0
      - replica:
          replicaCount: 2
      - master:
          configuration: |
            appendfsync everysec
            tcp-keepalive 0
